CREATE DATABASE QLDIEM
GO
USE QLDIEM
GO
IF OBJECT_ID('tblSV') IS NOT NULL
	DROP TABLE tblSV
GO
CREATE TABLE tblSV(
MASV VARCHAR(5),
HOTEN NVARCHAR(50),
EMAIL VARCHAR(50),
DT VARCHAR(15),
GT NVARCHAR(5),
DCHI NVARCHAR(100),
CONSTRAINT PK_tblSV PRIMARY KEY (MASV)
)
IF OBJECT_ID('tblDIEM') IS NOT NULL
	DROP TABLE tblDIEM
GO
CREATE TABLE tblDIEM(
ID INT IDENTITY(1,1) ,
MASV VARCHAR(5),
HOTEN NVARCHAR(50),
MARKTA FLOAT,
MARKTIN FLOAT,
MARKTC FLOAT,
CONSTRAINT PK_tblDIEM PRIMARY KEY (ID ),
CONSTRAINT FK_tblDIEM_tblSV FOREIGN KEY (MASV) REFERENCES tblSV
)
IF OBJECT_ID('tblUSER') IS NOT NULL
	DROP TABLE tblUSER
go
CREATE TABLE tblUSER(
USERNAME VARCHAR(50),
PASS VARCHAR(50),
CV NVARCHAR(50),
CONSTRAINT PK_tblUSER PRIMARY KEY (USERNAME)
)
select * from tblDIEM
select * from tblSV
select * from tblUSER
delete tblDIEM
delete tblSV
insert into tblUSER values('linh','123',N'GIÁO VIÊN'),
							('hihi','234',N'ĐÀO TẠO')

